group_project_6A/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from oneWordStory import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('oneWordStory/', include('oneWordStory.urls')),
]

oneWordStory/urls.py
from django.urls import path
from oneWordStory import views

app_name = 'oneWordStory'


urlpatterns = [
    path('', views.home, name='home'),
    path('story/add_story/', views.add_story, name='add_story'),
    path('account/register/', views.register, name='register'),
    path('account/login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('story/<slug:story_name_slug>/', views.show_story, name='show_story'),
    path('like_story/', views.LikeStoryView.as_view(), name='like_story'),
    path('search', views.search, name='search'),
]

rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'


urlpatterns = [
    path('', views.home, name='home'),
    path('add_story/', views.add_story, name='add_story'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),


]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
		{% block title_block %}
		<title>One Word Story</title>
		{% endblock %}
		<link rel="stylesheet" href="{% static "css/base.css" %}" />
    </head>
    <body>
		 <div class="header">
			<a href="{% url 'oneWordStory:home' %}" class="logo"><img src="{% static 'images/1wslogo.jpg' %}"  class="logo"/>One Word Story</a>
			<div class="header-right">
				{% if user.is_authenticated %}
				<a href="{% url 'oneWordStory:add_story' %}" class="headlink">Add a New Story</a>
				<a href="{% url 'oneWordStory:logout' %}" class="headlink">Logout</a>
				{% else %}
				<a href="{% url 'oneWordStory:register' %}" class="headlink">Sign Up</a>
				<a href="{% url 'oneWordStory:login' %}" class="headlink">Login</a>
				{% endif %}
				<a href="{% url 'oneWordStory:search' %}" class="headlink">Search</a>
			</div>
		</div> 
        <div class="bodyblock">
			{% block body_block %}
			{% endblock %}
        </div>
		<script src="{% static "js/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
		<script src="{% static "js/ows-ajax.js" %}" crossorigin="anonymous"></script>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<h1>Welcome to One Word Story!</h1>
Take part in a collaborative literature project, right from your web browser<br />
Just sign up for a free account and write with people across the world, word by word
<br><h2>Featured Stories:</h2>
<ul>
	{%for story in featuredStories %}
		<li>
			<a href="{% url 'oneWordStory:show_story' story.slug %}"> {{ story.title }}</a>
		</li>
	{% endfor %}
</ul>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %}
<title>Search</title>
{% endblock %}
{% block body_block %}
<h1>Search</h1>
Search by title for stories
<form method="get" action="{% url 'oneWordStory:search' %}">
<input type="text" name="s">
<input type="submit" value="Search">
{% if results %}
<br><h2>Results:</h2>
<ul>
	{%for story in results %}
		<li>
			<a href="{% url 'oneWordStory:show_story' story.slug %}"> {{ story.title }}</a>
		</li>
	{% endfor %}
</ul>
{% endif %}
{% endblock %}